apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pyapp.sareno.dev
spec:
  secretName: pyapp.sareno.dev
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - pyapp.sareno.dev
